export interface CelebrantProfile {
  id: number;
  name: string;
  type: string;
  city: string;
  region: string;
  country: 'UK' | 'Ireland';
  location: string;
  website?: string;
  image: string;
  description: string;
  fullDescription: string;
  specialties: string[];
  yearsExperience: number;
  ceremoniesPerformed: number;
  rating: number;
  slug?: string;
}

export const celebrants: CelebrantProfile[] = [
  {
    id: 1,
    name: 'Isla Hart',
    type: 'Luxury City Weddings',
    city: 'London',
    region: 'England',
    country: 'UK',
    location: 'London, UK',
    website: 'https://islahartcelebrant.co.uk',
    image: 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
    description: 'Modern, fashion-forward ceremonies for couples who want the London skyline as their backdrop.',
    fullDescription: 'I craft chic city ceremonies that feel like a magazine editorial while staying deeply personal. From rooftop vows in Shoreditch to timeless halls in Westminster, every script is tailored to your story and your guests.',
    specialties: ['Luxury Weddings', 'Rooftop Ceremonies', 'Editorial Styling', 'City Elopements'],
    yearsExperience: 9,
    ceremoniesPerformed: 320,
    rating: 4.9,
  },
  {
    id: 2,
    name: 'Noah Clarke',
    type: 'Story-Driven Weddings',
    city: 'Manchester',
    region: 'England',
    country: 'UK',
    location: 'Manchester, UK',
    website: 'https://noahclarkecelebrant.co.uk',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    description: 'Northern warmth and inclusive ceremonies that feel like your favourite gig night.',
    fullDescription: 'My ceremonies feel like the best Manchester nights: honest, heartfelt, and full of music. I work with indie couples, blended families, and anyone who wants a ceremony with real personality.',
    specialties: ['Alternative Weddings', 'Music-Led Ceremonies', 'Inclusive & LGBTQ+', 'City Venues'],
    yearsExperience: 7,
    ceremoniesPerformed: 240,
    rating: 4.8,
  },
  {
    id: 3,
    name: 'Priya Sharma',
    type: 'Interfaith & Cultural',
    city: 'Birmingham',
    region: 'England',
    country: 'UK',
    location: 'Birmingham, UK',
    website: 'https://priyasharmacelebrant.co.uk',
    image: 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80&sat=-30',
    description: 'Graceful fusion of Hindu, Sikh, and Western traditions with multilingual hosting.',
    fullDescription: 'Raised in a multilingual family, I help you honour every branch of your heritage. Expect carefully explained rituals, joyful pacing, and ceremonies where every guest feels included.',
    specialties: ['Interfaith Ceremonies', 'Multilingual Hosting', 'Cultural Rituals', 'Family Blending'],
    yearsExperience: 10,
    ceremoniesPerformed: 410,
    rating: 5,
  },
  {
    id: 4,
    name: 'Eilidh Fraser',
    type: 'Highland Traditions',
    city: 'Edinburgh',
    region: 'Scotland',
    country: 'UK',
    location: 'Edinburgh, Scotland',
    website: 'https://eilidhfraser.scot',
    image: 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80&sat=-20&hue=10',
    description: 'Celtic handfasting and castle weddings with cinematic flair.',
    fullDescription: 'From Arthur�s Seat sunrises to candlelit castles, I blend Gaelic blessings with modern vows. Every script is researched, historically respectful, and delivered with warmth.',
    specialties: ['Celtic Rituals', 'Castle Weddings', 'Elopements', 'Gaelic Blessings'],
    yearsExperience: 11,
    ceremoniesPerformed: 365,
    rating: 4.9,
  },
  {
    id: 5,
    name: 'Callum Reid',
    type: 'Modern Scottish Weddings',
    city: 'Glasgow',
    region: 'Scotland',
    country: 'UK',
    location: 'Glasgow, Scotland',
    website: 'https://callumreid.co.uk',
    image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80',
    description: 'Urban, design-led ceremonies with a Glaswegian heartbeat.',
    fullDescription: 'Think bold scripts, artful staging, and ceremonies that sound like you. I champion LGBTQ+ couples and creatives who want to break the mould.',
    specialties: ['Modern Vows', 'City Venues', 'LGBTQ+ Inclusive', 'Design-Led'],
    yearsExperience: 6,
    ceremoniesPerformed: 180,
    rating: 4.8,
  },
  {
    id: 6,
    name: 'Carys Hughes',
    type: 'Bilingual Welsh Ceremonies',
    city: 'Cardiff',
    region: 'Wales',
    country: 'UK',
    location: 'Cardiff, Wales',
    website: 'https://caryshughes.wales',
    image: 'https://images.unsplash.com/photo-1471115853179-bb1d604434e0?auto=format&fit=crop&w=1200&q=80',
    description: 'Warm, musical ceremonies delivered in Welsh and English.',
    fullDescription: 'I weave Welsh poetry, songs, and family history into ceremonies that feel like home. Perfect for coastal vows, barn weddings, and anyone proud of their roots.',
    specialties: ['Welsh/English Bilingual', 'Coastal Weddings', 'Family Stories', 'Poetry'],
    yearsExperience: 8,
    ceremoniesPerformed: 260,
    rating: 4.9,
  },
  {
    id: 7,
    name: 'Finn Gallagher',
    type: 'Celtic Ceremonies',
    city: 'Belfast',
    region: 'Northern Ireland',
    country: 'UK',
    location: 'Belfast, Northern Ireland',
    website: 'https://finngallagher.co.uk',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
    description: 'Inclusive ceremonies for cross-community couples with live music touches.',
    fullDescription: 'Raised in Belfast, I specialise in ceremonies that honour Catholic, Protestant, and secular backgrounds with equal respect. Expect humour, history, and a few fiddle tunes.',
    specialties: ['Cross-Community', 'Music-Led', 'Celtic Rituals', 'Outdoor Venues'],
    yearsExperience: 12,
    ceremoniesPerformed: 430,
    rating: 4.9,
  },
  {
    id: 8,
    name: 'Oliver West',
    type: 'Sustainable Weddings',
    city: 'Bristol',
    region: 'England',
    country: 'UK',
    location: 'Bristol, UK',
    website: 'https://oliverwestcelebrant.co.uk',
    image: 'https://images.unsplash.com/photo-1491557345352-5929e343eb89?auto=format&fit=crop&w=1200&q=80',
    description: 'Eco-first ceremonies with local suppliers and low-footprint scripts.',
    fullDescription: 'I help eco-conscious couples design ceremonies that tread lightly: local florals, vegan-friendly rituals, and paperwork handled with zero fuss.',
    specialties: ['Eco Weddings', 'Outdoor Ceremonies', 'Elopements', 'Sustainability'],
    yearsExperience: 5,
    ceremoniesPerformed: 140,
    rating: 4.7,
  },
  {
    id: 9,
    name: 'Layla Ahmed',
    type: 'Interfaith (Muslim/Christian)',
    city: 'Leeds',
    region: 'England',
    country: 'UK',
    location: 'Leeds, UK',
    website: 'https://laylaahmedcelebrant.co.uk',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80&sat=-15',
    description: 'Bringing families together with clear, gentle hosting and translated vows.',
    fullDescription: 'From Nikah to church blessings, I handle the nuances so you can relax. Scripts are double-checked with families and faith leaders for accuracy and respect.',
    specialties: ['Interfaith Weddings', 'Family Liaison', 'Translation Support', 'Cultural Sensitivity'],
    yearsExperience: 9,
    ceremoniesPerformed: 280,
    rating: 4.9,
  },
  {
    id: 10,
    name: 'Tom Walker',
    type: 'Modern Industrial Weddings',
    city: 'Newcastle',
    region: 'England',
    country: 'UK',
    location: 'Newcastle, UK',
    website: 'https://tomwalkercelebrant.co.uk',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
    description: 'Warehouse, gallery, and riverside ceremonies with Geordie charm.',
    fullDescription: 'I love transforming industrial spaces into romantic stages. Expect tight run-sheets, great sound, and scripts that make everyone laugh and cry.',
    specialties: ['Industrial Venues', 'Riverside Vows', 'Run-Sheet Planning', 'Humour & Heart'],
    yearsExperience: 6,
    ceremoniesPerformed: 190,
    rating: 4.8,
  },
  {
    id: 11,
    name: 'Sienna Brooks',
    type: 'Seaside Elopements',
    city: 'Brighton',
    region: 'England',
    country: 'UK',
    location: 'Brighton, UK',
    website: 'https://siennacelebrates.co.uk',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80&sat=15',
    description: 'Sunrise pier vows, barefoot beach ceremonies, and colourful micro-weddings.',
    fullDescription: 'I specialise in intimate seaside ceremonies that feel spontaneous yet flawlessly run. Permits, tide times, and cosy reception ideas are handled for you.',
    specialties: ['Beach Weddings', 'Elopements', 'Micro-Weddings', 'LGBTQ+ Friendly'],
    yearsExperience: 7,
    ceremoniesPerformed: 210,
    rating: 4.9,
  },
  {
    id: 12,
    name: "Grace O'Sullivan",
    type: 'Funeral & Celebration of Life',
    city: 'Dublin',
    region: 'Leinster',
    country: 'Ireland',
    location: 'Dublin, Ireland',
    website: 'https://graceosullivan.ie',
    image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
    description: 'Gentle, story-led farewells grounded in Irish warmth.',
    fullDescription: 'I gather memories from every generation and weave them into ceremonies full of humour, music, and respect. Available for home vigils and eco-burials.',
    specialties: ['Funeral Services', 'Celebration of Life', 'Eco Burials', 'Storytelling'],
    yearsExperience: 14,
    ceremoniesPerformed: 520,
    rating: 5,
  },
  {
    id: 13,
    name: 'Seamus Byrne',
    type: 'Traditional Irish Weddings',
    city: 'Cork',
    region: 'Munster',
    country: 'Ireland',
    location: 'Cork, Ireland',
    website: 'https://seamusbyrne.ie',
    image: 'https://images.unsplash.com/photo-1500534314211-30c70bdf21b7?auto=format&fit=crop&w=1200&q=80',
    description: 'Handfasting, ring-warming, and Claddagh-inspired vows by the coast.',
    fullDescription: 'I blend Cork charm with timeless rituals and live trad music. Perfect for barn weddings, coastal cliffs, and families wanting heart-first hosting.',
    specialties: ['Handfasting', 'Ring Warming', 'Trad Music', 'Coastal Venues'],
    yearsExperience: 13,
    ceremoniesPerformed: 405,
    rating: 4.9,
  },
  {
    id: 14,
    name: 'Aoife Daly',
    type: 'Bilingual (Irish/English)',
    city: 'Galway',
    region: 'Connacht',
    country: 'Ireland',
    location: 'Galway, Ireland',
    website: 'https://aoifedaly.ie',
    image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80&sat=-25',
    description: 'West coast romance with Gaeilge blessings and folk references.',
    fullDescription: 'From Salthill to Connemara, I create ceremonies that honour Irish language and landscape. Expect lyrical scripts, slow pacing, and music pairings.',
    specialties: ['Irish Language', 'Coastal Ceremonies', 'Music Pairing', 'Elopements'],
    yearsExperience: 8,
    ceremoniesPerformed: 230,
    rating: 4.8,
  },
  {
    id: 15,
    name: 'Maeve Ryan',
    type: 'Modern Irish Ceremonies',
    city: 'Limerick',
    region: 'Munster',
    country: 'Ireland',
    location: 'Limerick, Ireland',
    website: 'https://maeveryancelebrant.ie',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80&sat=-10',
    description: 'Crisp, contemporary scripts with a nod to local tradition.',
    fullDescription: 'I specialise in modern venues, hotel terraces, and riverside spaces around Limerick. Every ceremony is timed to the minute for stress-free days.',
    specialties: ['Modern Venues', 'Hotel Weddings', 'Timeline Planning', 'Family-Focused'],
    yearsExperience: 6,
    ceremoniesPerformed: 175,
    rating: 4.7,
  },
  {
    id: 16,
    name: 'Ciara Walsh',
    type: 'Romantic Storytelling',
    city: 'Waterford',
    region: 'Munster',
    country: 'Ireland',
    location: 'Waterford, Ireland',
    website: 'https://ciarawalsh.ie',
    image: 'https://images.unsplash.com/photo-1529429617124-aee99cfd1eaf?auto=format&fit=crop&w=1200&q=80',
    description: 'Historic city backdrops, candlelit scripts, and gentle humour.',
    fullDescription: 'Inspired by Waterford�s history, I write ceremonies that feel elegant without being stiff. Perfect for glasshouse venues, manors, and intimate courtyards.',
    specialties: ['Historic Venues', 'Evening Ceremonies', 'Storytelling', 'Intimate Weddings'],
    yearsExperience: 7,
    ceremoniesPerformed: 190,
    rating: 4.8,
  },
  {
    id: 17,
    name: 'Liam Kavanagh',
    type: 'Wild Atlantic Elopements',
    city: 'Killarney',
    region: 'Kerry',
    country: 'Ireland',
    location: 'Killarney, Ireland',
    website: 'https://liamkavanagh.ie',
    image: 'https://images.unsplash.com/photo-1500534314211-30c70bdf21b7?auto=format&fit=crop&w=1200&q=80&sat=-10',
    description: 'Adventure elopements in the national park and along the Ring of Kerry.',
    fullDescription: 'I guide you through permits, secluded spots, and wet-weather plans. Your vows will feel intimate even when the Atlantic winds roar.',
    specialties: ['Adventure Elopements', 'Hiking Access', 'Intimate Vows', 'Dawn/Dusk Ceremonies'],
    yearsExperience: 5,
    ceremoniesPerformed: 120,
    rating: 4.8,
  },
  {
    id: 18,
    name: 'Daniel Nolan',
    type: 'Heritage Weddings',
    city: 'Kilkenny',
    region: 'Leinster',
    country: 'Ireland',
    location: 'Kilkenny, Ireland',
    website: 'https://danielnolan.ie',
    image: 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=1200&q=80',
    description: 'Medieval venues, castle courtyards, and artisan local touches.',
    fullDescription: 'Kilkenny�s craft scene inspires my ceremonies. Think hand-thrown unity cups, local musicians, and scripts steeped in your ancestry.',
    specialties: ['Castle Venues', 'Unity Rituals', 'Local Makers', 'Ancestry Stories'],
    yearsExperience: 9,
    ceremoniesPerformed: 260,
    rating: 4.9,
  },
  {
    id: 19,
    name: "Niamh O'Donnell",
    type: 'Seaside Ceremonies',
    city: 'Sligo',
    region: 'Connacht',
    country: 'Ireland',
    location: 'Sligo, Ireland',
    website: 'https://niamhodonnell.ie',
    image: 'https://images.unsplash.com/photo-1500534314211-30c70bdf21b7?auto=format&fit=crop&w=1200&q=80&sat=-5',
    description: 'Atlantic backdrops, poetry, and surfer-friendly elopements.',
    fullDescription: 'I help couples marry by the sea with barefoot ease. Ceremonies include Yeats nods, tide checks, and cosy indoor plans just in case.',
    specialties: ['Beach Weddings', 'Poetic Scripts', 'Elopements', 'Weather Planning'],
    yearsExperience: 6,
    ceremoniesPerformed: 160,
    rating: 4.8,
  },
  {
    id: 20,
    name: 'Patrick McCarthy',
    type: 'Garden & Manor Weddings',
    city: 'Wexford',
    region: 'Leinster',
    country: 'Ireland',
    location: 'Wexford, Ireland',
    website: 'https://patrickmccarthy.ie',
    image: 'https://images.unsplash.com/photo-1500534314211-30c70bdf21b7?auto=format&fit=crop&w=1200&q=80&sat=-20',
    description: 'Sunlit gardens, glasshouse vows, and orchestra-backed aisles.',
    fullDescription: 'I collaborate with local string quartets and florists to stage ceremonies that feel cinematic. Perfect for manors, glasshouses, and private estates.',
    specialties: ['Garden Venues', 'Live Musicians', 'Private Estates', 'Cinematic Scripts'],
    yearsExperience: 12,
    ceremoniesPerformed: 340,
    rating: 4.9,
  },
  {
    id: 21,
    name: 'Amelia Brooks',
    type: 'Eco Woodland Weddings',
    city: 'Bristol',
    region: 'England',
    country: 'UK',
    location: 'Bristol, UK',
    website: 'https://ameliabrookscelebrant.co.uk',
    image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=1200&q=80',
    description: 'Nature-led ceremonies with eco-friendly rituals and local musicians.',
    fullDescription: 'From arboretum vows to woodland clearings, I design ceremonies that tread lightly and feel deeply personal. Expect sustainable styling, acoustic music, and mindful pacing.',
    specialties: ['Eco-Friendly', 'Outdoor Weddings', 'Handfasting', 'Acoustic Music'],
    yearsExperience: 8,
    ceremoniesPerformed: 210,
    rating: 4.8,
  },
  {
    id: 22,
    name: 'Zachary Ellis',
    type: 'Modern Industrial Chic',
    city: 'Leeds',
    region: 'England',
    country: 'UK',
    location: 'Leeds, UK',
    website: 'https://zacharyellisceremonies.com',
    image: 'https://images.unsplash.com/photo-1496285412000-3e2291e2e8c8?auto=format&fit=crop&w=1200&q=80',
    description: 'Loft venues, converted mills, and bold contemporary scripts.',
    fullDescription: 'I turn industrial spaces into warm, story-driven ceremonies. Lighting plans, pacing, and inclusive storytelling ensure everyone feels part of the moment.',
    specialties: ['Industrial Venues', 'Inclusivity', 'Storytelling', 'Lighting Design'],
    yearsExperience: 6,
    ceremoniesPerformed: 180,
    rating: 4.7,
  },
  {
    id: 23,
    name: 'Sophie Bennett',
    type: 'Heritage & Cathedral',
    city: 'Newcastle',
    region: 'England',
    country: 'UK',
    location: 'Newcastle, UK',
    website: 'https://sophiebennettcelebrant.com',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    description: 'Historic halls, cathedrals, and black-tie storytelling with warmth.',
    fullDescription: 'I blend formal settings with human warmth�clear soundchecks, elegant scripts, and calm coordination with venue teams.',
    specialties: ['Formal Venues', 'Black-Tie', 'Sound Design', 'Rehearsals'],
    yearsExperience: 9,
    ceremoniesPerformed: 260,
    rating: 4.9,
  },
  {
    id: 24,
    name: 'Olivia Grant',
    type: 'Story-Forward Belfast',
    city: 'Belfast',
    region: 'Northern Ireland',
    country: 'UK',
    location: 'Belfast, Northern Ireland',
    website: 'https://oliviagrantceremonies.co.uk',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80',
    description: 'Urban Belfast love stories with live music cues and bilingual touches.',
    fullDescription: 'From Cathedral Quarter rooftops to botanic gardens, I script ceremonies that feel like a well-produced show�clear cues, live music timing, and humour.',
    specialties: ['Urban Venues', 'Live Music', 'Bilingual', 'Humour'],
    yearsExperience: 7,
    ceremoniesPerformed: 190,
    rating: 4.8,
  },
  {
    id: 25,
    name: 'Ethan Price',
    type: 'Classic Manor Weddings',
    city: 'Bath',
    region: 'England',
    country: 'UK',
    location: 'Bath, UK',
    website: 'https://ethanpricecelebrant.com',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
    description: 'Georgian manors, string quartets, and timeless ceremony pacing.',
    fullDescription: 'I specialise in heritage manors and hotel terraces, coordinating with musicians and planners to deliver polished, elegant ceremonies.',
    specialties: ['Manor Houses', 'String Quartets', 'Luxury Hotels', 'Timeline Management'],
    yearsExperience: 10,
    ceremoniesPerformed: 320,
    rating: 4.9,
  },
  {
    id: 26,
    name: 'Freya Collins',
    type: 'Historic City Romance',
    city: 'York',
    region: 'England',
    country: 'UK',
    location: 'York, UK',
    website: 'https://freyacollinsceremonies.com',
    image: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
    description: 'City walls, libraries, and candlelit evening ceremonies.',
    fullDescription: 'York inspires my scripts: literary nods, candlelight, and steady pacing so guests feel immersed and relaxed.',
    specialties: ['Evening Ceremonies', 'Literary Readings', 'Historic Venues', 'Candles & Lighting'],
    yearsExperience: 8,
    ceremoniesPerformed: 230,
    rating: 4.8,
  },
  {
    id: 27,
    name: "Ronan O'Shea",
    type: 'Coastal Celtic Rituals',
    city: 'Cork',
    region: 'Munster',
    country: 'Ireland',
    location: 'Cork, Ireland',
    website: 'https://ronanosheaceremonies.ie',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
    description: 'Atlantic views, Celtic blessings, and relaxed coastal pacing.',
    fullDescription: 'I guide couples through sea-facing ceremonies with tide-aware timing, Celtic rituals, and bilingual welcomes.',
    specialties: ['Coastal Weddings', 'Celtic Rituals', 'Bilingual', 'Weather Plans'],
    yearsExperience: 9,
    ceremoniesPerformed: 260,
    rating: 4.9,
  },
  {
    id: 28,
    name: 'Saoirse Byrne',
    type: 'Gaelic & Folk Traditions',
    city: 'Galway',
    region: 'Connacht',
    country: 'Ireland',
    location: 'Galway, Ireland',
    website: 'https://saoirsebyrneceremonies.ie',
    image: 'https://images.unsplash.com/photo-1471115853179-bb1d604434e0?auto=format&fit=crop&w=1200&q=80',
    description: 'Gaelic songs, trad musicians, and intimate coastal elopements.',
    fullDescription: 'I weave Gaeilge, folk music, and family stories into ceremonies that feel like a fireside session by the bay.',
    specialties: ['Gaelic Language', 'Traditional Music', 'Elopements', 'Family Storytelling'],
    yearsExperience: 7,
    ceremoniesPerformed: 180,
    rating: 4.8,
  },
  {
    id: 29,
    name: 'Aidan Murphy',
    type: 'Wild Atlantic Elopements',
    city: 'Donegal',
    region: 'Ulster',
    country: 'Ireland',
    location: 'Donegal, Ireland',
    website: 'https://aidanmurphycelebrant.ie',
    image: 'https://images.unsplash.com/photo-1500534314211-30c70bdf21b7?auto=format&fit=crop&w=1200&q=80',
    description: 'Clifftop vows, dawn hikes, and cinematic photography cues.',
    fullDescription: 'I scout cliff paths and beaches, manage safety and timing, and script vows that feel intimate against the Atlantic.',
    specialties: ['Adventure Elopements', 'Hiking Access', 'Sunrise/Sunset', 'Photo Coordination'],
    yearsExperience: 6,
    ceremoniesPerformed: 150,
    rating: 4.8,
  },
  {
    id: 30,
    name: 'Eimear Kelly',
    type: 'Cross-Border Celebrations',
    city: 'Derry',
    region: 'Northern Ireland',
    country: 'UK',
    location: 'Derry, Northern Ireland',
    website: 'https://eimearkellycelebrant.com',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80&sat=-5',
    description: 'Cross-border logistics, inclusive vows, and calm hosting style.',
    fullDescription: 'From castle hotels to countryside barns, I handle paperwork guidance, inclusive wording, and calm day-of coordination across NI/ROI.',
    specialties: ['Cross-Border', 'Logistics', 'Inclusive Language', 'Calm Hosting'],
    yearsExperience: 11,
    ceremoniesPerformed: 340,
    rating: 5.0,
  },
];



